#ifndef REALJOYSTICKSGLOBAL_H
#define REALJOYSTICKSGLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REALJOYSTICKS_LIBRARY)
# define REALJOYSTICKS_EXPORT Q_DECL_EXPORT
#else
# define REALJOYSTICKS_EXPORT Q_DECL_IMPORT
#endif

#endif // REALJOYSTICKSGLOBAL_H
